"""create job syllabus

Revision ID: 0f5cb9e88d76
Revises: 11e3f545f4e1
Create Date: 2026-08-31 15:28:34.667724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5cb9e88d76'
down_revision: Union[str, Sequence[str], None] = '11e3f545f4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_syllabus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('exam_pattern_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('sub_topic_name', sa.String(length=200), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('weightage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('reference_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_pattern_id'], ['job_exam_pattern.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_syllabus_exam_pattern_id'), 'job_syllabus', ['exam_pattern_id'], unique=False)
    op.create_index(op.f('ix_job_syllabus_job_id'), 'job_syllabus', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_syllabus_job_id'), table_name='job_syllabus')
    op.drop_index(op.f('ix_job_syllabus_exam_pattern_id'), table_name='job_syllabus')
    op.drop_table('job_syllabus')
    # ### end Alembic commands ###
