"""create job exam pattern

Revision ID: 11e3f545f4e1
Revises: e077c25d6b28
Create Date: 2026-08-31 15:18:43.639483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e3f545f4e1'
down_revision: Union[str, Sequence[str], None] = 'e077c25d6b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_exam_pattern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('exam_mode', sa.String(length=30), nullable=True),
    sa.Column('exam_type', sa.String(length=30), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('negative_marks', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('qualifying_marks', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_exam_pattern_job_id'), 'job_exam_pattern', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_exam_pattern_job_id'), table_name='job_exam_pattern')
    op.drop_table('job_exam_pattern')
    # ### end Alembic commands ###
