"""add job eligibility relationship

Revision ID: 23c612d882b2
Revises: 8fed9159e180
Create Date: 2026-08-22 15:05:30.589728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c612d882b2'
down_revision: Union[str, Sequence[str], None] = '8fed9159e180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_eligibility_job_id'), 'job_eligibility', ['job_id'], unique=False)
    op.create_foreign_key(None, 'job_eligibility', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_eligibility', type_='foreignkey')
    op.drop_index(op.f('ix_job_eligibility_job_id'), table_name='job_eligibility')
    # ### end Alembic commands ###
