"""create initial database tables

Revision ID: a52e47067a07
Revises: 
Create Date: 2026-08-18 14:53:00.299916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52e47067a07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_eligibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('age_relaxation_available', sa.Boolean(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('required_degree', sa.String(length=150), nullable=True),
    sa.Column('minimum_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('experience_required', sa.Boolean(), nullable=False),
    sa.Column('minimum_experience_years', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('physical_standard_required', sa.Boolean(), nullable=False),
    sa.Column('medical_fitness_required', sa.Boolean(), nullable=False),
    sa.Column('gender_eligibility', sa.String(length=20), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_code', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_mode', sa.String(length=20), nullable=True),
    sa.Column('application_start_date', sa.Date(), nullable=True),
    sa.Column('application_end_date', sa.Date(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('application_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('official_notification_url', sa.Text(), nullable=True),
    sa.Column('official_apply_url', sa.Text(), nullable=True),
    sa.Column('official_website', sa.Text(), nullable=True),
    sa.Column('job_status', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_table('learning_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=True),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('test_type', sa.String(length=30), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('negative_marks', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('passing_marks', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ai_focus_area', sa.String(length=100), nullable=True),
    sa.Column('target_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('roadmap_title', sa.String(length=200), nullable=False),
    sa.Column('roadmap_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_exam_date', sa.Date(), nullable=True),
    sa.Column('total_duration_days', sa.Integer(), nullable=True),
    sa.Column('total_stages', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=True),
    sa.Column('roadmap_stage_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('task_title', sa.String(length=200), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completion_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_name', sa.String(length=150), nullable=False),
    sa.Column('topic_code', sa.String(length=30), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('weightage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('subjects')
    op.drop_table('study_tasks')
    op.drop_table('roadmaps')
    op.drop_table('roadmap_stages')
    op.drop_table('mock_tests')
    op.drop_table('learning_resources')
    op.drop_table('jobs')
    op.drop_table('job_eligibility')
    # ### end Alembic commands ###
